### PR TITLE
Prepare 0.1.1-4 release

### PR DESCRIPTION
**Pull request by lukpueh**
* Update downstream files
* Add Dockerfile to make future downstream packaging easier See doc header for usage details.

### CODE REVIEW

**Comment by lukpueh** [comment]
Release files uploaded to mentors: https://mentors.debian.net/package/apt-transport-in-toto/

**Comment by h01ger** [comment]
On Wed, Nov 08, 2023 at 08:50:05AM -0800, Lukas Pühringer wrote:
> Release files uploaded to mentors: https://mentors.debian.net/package/apt-transport-in-toto/

unfortunatly this fails to build against current unstable:

 dpkg-source -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: verifying ./apt-transport-in-toto_0.1.1.orig.tar.gz.asc
dpkg-source: info: building apt-transport-in-toto using existing ./apt-transport-in-toto_0.1.1.orig.tar.gz
dpkg-source: info: building apt-transport-in-toto using existing ./apt-transport-in-toto_0.1.1.orig.tar.gz.asc
dpkg-source: info: building apt-transport-in-toto in apt-transport-in-toto_0.1.1-4.debian.tar.xz
dpkg-source: info: building apt-transport-in-toto in apt-transport-in-toto_0.1.1-4.dsc
 debian/rules binary
dh binary
   dh_update_autotools_config
   dh_autoreconf
   debian/rules override_dh_auto_test
make[1]: Entering directory '/build/apt-transport-in-toto-0.1.1'
python3-coverage run -m unittest discover
EE
======================================================================
ERROR: tests.test_intoto (unittest.loader._FailedTest.tests.test_intoto)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_intoto
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/build/apt-transport-in-toto-0.1.1/tests/test_intoto.py", line 30, in <module>
    import intoto
  File "/build/apt-transport-in-toto-0.1.1/intoto.py", line 118, in <module>
    import in_toto.verifylib
  File "/usr/lib/python3/dist-packages/in_toto/verifylib.py", line 38, in <module>
    import in_toto.runlib
  File "/usr/lib/python3/dist-packages/in_toto/runlib.py", line 46, in <module>
    import securesystemslib.process
ModuleNotFoundError: No module named 'securesystemslib.process'


======================================================================
ERROR: tests.test_units (unittest.loader._FailedTest.tests.test_units)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_units
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/build/apt-transport-in-toto-0.1.1/tests/test_units.py", line 26, in <module>
    import intoto
  File "/build/apt-transport-in-toto-0.1.1/intoto.py", line 118, in <module>
    import in_toto.verifylib
  File "/usr/lib/python3/dist-packages/in_toto/verifylib.py", line 38, in <module>
    import in_toto.runlib
  File "/usr/lib/python3/dist-packages/in_toto/runlib.py", line 46, in <module>
    import securesystemslib.process
ModuleNotFoundError: No module named 'securesystemslib.process'


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
make[1]: *** [debian/rules:14: override_dh_auto_test] Error 1
make[1]: Leaving directory '/build/apt-transport-in-toto-0.1.1'
make: *** [debian/rules:9: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

No mas pobres en un pais rico!

**Comment by h01ger** [comment]
It looks like the build uses the new securesystemslib accepted last night [1] but not yet the new in-toto accepted this morning [2].

If you rebuild it should work.

Thanks
Lukas


[1] https://tracker.debian.org/news/1478556/accepted-python-securesystemslib-0280-1-source-into-unstable/
[2] https://tracker.debian.org/news/1478697/accepted-in-toto-200-1-source-into-unstable/

**Comment by h01ger** [comment]
On Wed, Nov 15, 2023 at 01:40:41AM -0800, Holger Levsen wrote:
> It looks like the build uses the new securesystemslib accepted last night [1] but not yet the new in-toto accepted this morning [2].
> If you rebuild it should work.

you could/should have adjusted the build-depends in d/control accordingly.

but will try again in 5h...


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

Homophobia is a sin against god.

**Comment by lukpueh** [comment]
> you could/should have adjusted the build-depends in d/control accordingly.

Not sure how though. The individual requirements constraints in the latest in-toto and apt-transport-in-toto releases are valid. The issue is that the previous in-toto release no longer works with the latest securesystemslib release. This means, apt-transport-in-toto could either use
- old in-toto (>= 1.0.0)  with old securesystemslib (== 0.26.0),  or
- or new in-toto (>=  1.3.2) with new securesystemslib (>= 0.26.0)

The easiest fix would to require the latest in-toto. Let me know, if I should change d/control here.

And thanks for uploading, btw! ❤️

**Comment by h01ger** [comment]
On Wed, Nov 15, 2023 at 04:09:10AM -0800, Lukas Pühringer wrote:
> > you could/should have adjusted the build-depends in d/control accordingly.
> Not sure how though. The individual requirements constraints in the latest in-toto and apt-transport-in-toto releases are valid. The issue is that the previous in-toto release no longer works with the latest securesystemslib release. This means, apt-transport-in-toto could either use
> - old in-toto (>= 1.0.0)  with old securesystemslib (== 0.26.0),  or
> - or new in-toto (>=  1.3.2) with new securesystemslib (>= 0.26.0)

ah. now it makes sense!
 
> The easiest fix would to require the latest in-toto. Let me know, if I should change d/control here.

no, thanks.

> And thanks for uploading, btw! ❤️ 

sure thing! thanks for in-toto! <3

:)

please also push those debian debian branches after I uploaded.


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

“It's easy to be a naive idealist. It's easy to be a cynical realist. It's
 quite another thing to have no illusions and still hold the inner flame.”
 (Marie-Louise von Franz)

**Comment by lukpueh** [comment]
Released: https://tracker.debian.org/news/1478755/accepted-apt-transport-in-toto-011-4-source-into-unstable/

**Pull request merged**
